name: Push release to container registry

on:
  release:
    types: [published]

jobs:
  mvn-build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Clean Compile & Test
        run: mvn --batch-mode --update-snapshots clean compile test
      - name: Build and push image
        run: mvn --batch-mode jib:build -Ppush-ghcr
        env:
            REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
            REGISTRY_USERNAME: ${{ github.actor }}
      - name: Done
        run: echo Image successfully pushed
